delivery_notes/urls.py
from django.urls import path

from .views import (
    DeliveryNoteListView,
    DeliveryNoteDetailView,
    DeliveryNoteCreateView,
    DeliveryNoteUpdateView,
    DeliveryNoteDeleteView,
)

app_name = 'delivery_notes'

urlpatterns = [
    path('', DeliveryNoteListView.as_view(), name='delivery_note_list'),
    path('<int:pk>/', DeliveryNoteDetailView.as_view(), name='delivery_note_detail'),
    path('create/', DeliveryNoteCreateView.as_view(), name='delivery_note_create'),
    path('<int:pk>/update/', DeliveryNoteUpdateView.as_view(), name='delivery_note_update'),
    path('<int:pk>/delete/', DeliveryNoteDeleteView.as_view(), name='delivery_note_delete'),
]

orders_manager/urls.py
# """orders_manager URL Configuration

# The `urlpatterns` list routes URLs to views. For more information please see:
#     https://docs.djangoproject.com/en/4.1/topics/http/urls/
# Examples:
# Function views
#     1. Add an import:  from my_app import views
#     2. Add a URL to urlpatterns:  path('', views.home, name='home')
# Class-based views
#     1. Add an import:  from other_app.views import Home
#     2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
# Including another URLconf
#     1. Import the include() function: from django.urls import include, path
#     2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
# """
# from django.contrib import admin
# from django.urls import path

# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('delivery_notes/', include('delivery_notes.urls')),
    # path('invoices/', include('invoices.urls')),
    # #path('purchase_orders/', include('purchase_orders.urls')),
    # path('users/', include('users.urls')),
]

purchase_orders/urls.py
# from django.urls import path

# from . import views

# urlpatterns = [
#     path('', views.index, name='index'),
# ]
from django.urls import path

from . import views

app_name = 'delivery_notes'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:delivery_note_id>/', views.detail, name='detail'),
    # add more paths as needed
]

stock_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('delivery_notes/', include('delivery_notes.urls', namespace='delivery_notes')),
]

delivery_notes/models.py
from django.db import models

class DeliveryNote(models.Model):
    delivery_note_number = models.CharField(max_length=50, unique=True)
    date = models.DateField()
    invoice_number = models.CharField(max_length=50)
    image = models.ImageField(upload_to='delivery_notes')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.delivery_note_number

    def save(self, *args, **kwargs):
        super(DeliveryNote, self).save(*args, **kwargs)

    @staticmethod
    def get_all_delivery_notes():
        return DeliveryNote.objects.all()

    @staticmethod
    def search_delivery_note_by_number(delivery_note_number):
        return DeliveryNote.objects.filter(delivery_note_number__icontains=delivery_note_number)

invoices/models.py
from django.db import models

class Invoice(models.Model):
    invoice_number = models.CharField(max_length=255)
    date = models.DateField()
    customer_name = models.CharField(max_length=255)
    item_name = models.CharField(max_length=255)
    quantity = models.PositiveIntegerField()
    unit_price = models.DecimalField(max_digits=10, decimal_places=2)

purchase_orders/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models

class User(models.Model):
    username = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    password = models.CharField(max_length=255)

delivery_notes/forms.py
from django import forms
from .models import DeliveryNote


class DeliveryNoteForm(forms.ModelForm):
    class Meta:
        model = DeliveryNote
        fields = ['delivery_note_number', 'date', 'invoice_number', 'image']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'})
        }

delivery_notes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.urls import reverse_lazy
from django.contrib import messages

from .models import DeliveryNote
from .forms import DeliveryNoteForm


class DeliveryNoteListView(View):
    def get(self, request):
        delivery_notes = DeliveryNote.objects.all()
        return render(request, 'delivery_notes/base.html', {'delivery_notes': delivery_notes})


class DeliveryNoteDetailView(View):
    def get(self, request, pk):
        delivery_note = get_object_or_404(DeliveryNote, pk=pk)
        return render(request, 'delivery_notes/detail.html', {'delivery_note': delivery_note})


class DeliveryNoteCreateView(View):
    def get(self, request):
        form = DeliveryNoteForm()
        return render(request, 'delivery_notes/delivery_note_create.html', {'form': form})

    def post(self, request):
        form = DeliveryNoteForm(request.POST)
        if form.is_valid():
            delivery_note = form.save()
            messages.success(request, 'Delivery note created successfully.')
            return redirect('delivery_notes:list')
        return render(request, 'delivery_notes/delivery_note_create.html', {'form': form})


class DeliveryNoteUpdateView(View):
    def get(self, request, pk):
        delivery_note = get_object_or_404(DeliveryNote, pk=pk)
        form = DeliveryNoteForm(instance=delivery_note)
        return render(request, 'delivery_notes/update.html', {'form': form})

    def post(self, request, pk):
        delivery_note = get_object_or_404(DeliveryNote, pk=pk)
        form = DeliveryNoteForm(request.POST, instance=delivery_note)
        if form.is_valid():
            delivery_note = form.save()
            messages.success(request, 'Delivery note updated successfully.')
            return redirect('delivery_notes:list')
        return render(request, 'delivery_notes/update.html', {'form': form})


class DeliveryNoteDeleteView(View):
    def get(self, request, pk):
        delivery_note = get_object_or_404(DeliveryNote, pk=pk)
        return render(request, 'delivery_notes/delete.html', {'delivery_note': delivery_note})

    def post(self, request, pk):
        delivery_note = get_object_or_404(DeliveryNote, pk=pk)
        delivery_note.delete()
        messages.success(request, 'Delivery note deleted successfully.')
        return redirect('delivery_notes:list')

invoices/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'invoices/index.html')

purchase_orders/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'purchase_orders/index.html')

users/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'users/index.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}Orders Manager{% endblock %}</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  {% block styles %}{% endblock %}
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Orders Manager</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    {% comment %} <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav"> 
         <li class="nav-item active">
          <a class="nav-link" href="{% url 'delivery_notes:index' %}">Delivery Notes</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'invoices:index' %}">Invoices</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'purchase_orders:index' %}">Purchase Orders</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:index' %}">Users</a>
        </li>
      </ul> 
    </div> {% endcomment %}
  </nav>
  <div class="container mt-4">
    {% block content %}{% endblock %}
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNVQ8ew" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  {% block scripts %}{% endblock %}
</body>
</html>

templates/delivery_notes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
  
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'delivery_notes:delivery_note_list' %}">Delivery Notes</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                 </li>
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNVQ8ew" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {% block js %}{% endblock %}
</body>
</html>

 
  </body>
</html>

templates/delivery_notes/create.html
{% extends "base.html" %}

{% block content %}
  <h1>Create Delivery Note</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
{% endblock %}

templates/delivery_notes/delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Delivery Note {{ delivery_note.pk }}</h1>
  <form method="POST">
    {% csrf_token %}
    <p>Are you sure you want to delete this delivery note?</p>
    <button type="submit">Yes, delete it</button>
    <a href="{% url 'delivery_notes:list' %}">No, take me back</a>
  </form>
{% endblock %}

templates/delivery_notes/delivery_note/delivery_note_create.html
{% extends "base.html" %}

{% block content %}
  <h1>Create Delivery Note</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
{% endblock %}

templates/delivery_notes/delivery_note/delivery_note_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Delivery Note {{ delivery_note.pk }}</h1>
  <form method="POST">
    {% csrf_token %}
    <p>Are you sure you want to delete this delivery note?</p>
    <button type="submit">Yes, delete it</button>
    <a href="{% url 'delivery_notes:list' %}">No, take me back</a>
  </form>
{% endblock %}

templates/delivery_notes/delivery_note/delivery_note_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>Delivery Note Details</h1>
  <p><strong>Delivery Note Number:</strong> {{ delivery_note.delivery_note_number }}</p>
  <p><strong>Supplier:</strong> {{ delivery_note.supplier }}</p>
  <p><strong>Delivery Date:</strong> {{ delivery_note.delivery_date }}</p>

  <hr>

  <h2>Items</h2>
  {% if delivery_note.items %}
    <ul>
      {% for item in delivery_note.items %}
        <li>{{ item.product_name }} - Quantity: {{ item.quantity }}</li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No items found.</p>
  {% endif %}
{% endblock %}

templates/delivery_notes/delivery_note/delivery_note_update.html
{% extends "base.html" %}

{% block content %}
  <h1>Edit Delivery Note {{ delivery_note.pk }}</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
{% endblock %}

templates/delivery_notes/delivery_note_create.html
{% extends 'index.html' %}

{% block content %}
  <h1>Delivery Notes</h1>
  <a href="{% url 'delivery_notes:delivery_note_create' %}" class="btn btn-primary mb-2">Create Delivery Note</a>
  
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Delivery Note Number</th>
        <th scope="col">Date Delivered</th>
        <th scope="col">Invoice Number</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      {% for delivery_note in delivery_notes %}
        <tr>
          <th scope="row">{{ delivery_note.id }}</th>
          <td>{{ delivery_note.delivery_note_number }}</td>
          <td>{{ delivery_note.date_delivered }}</td>
          <td>{{ delivery_note.invoice_number }}</td>
          <td>
            <a href="{% url 'delivery_note_detail' delivery_note.id %}" class="btn btn-primary">Details</a>
            <a href="{% url 'delivery_note_update' delivery_note.id %}" class="btn btn-secondary">Edit</a>
            <form action="{% url 'delivery_note_delete' delivery_note.id %}" method="post" class="d-inline">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger">Delete</button>
            </form>
          </td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="5">No delivery notes found.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

templates/delivery_notes/delivery_note_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Delivery Note {{ delivery_note.pk }}</h1>
  <form method="POST">
    {% csrf_token %}
    <p>Are you sure you want to delete this delivery note?</p>
    <button type="submit">Yes, delete it</button>
    <a href="{% url 'delivery_notes:list' %}">No, take me back</a>
  </form>
{% endblock %}

templates/delivery_notes/delivery_note_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>Delivery Note Details</h1>
  <p><strong>Delivery Note Number:</strong> {{ delivery_note.delivery_note_number }}</p>
  <p><strong>Supplier:</strong> {{ delivery_note.supplier }}</p>
  <p><strong>Delivery Date:</strong> {{ delivery_note.delivery_date }}</p>

  <hr>

  <h2>Items</h2>
  {% if delivery_note.items %}
    <ul>
      {% for item in delivery_note.items %}
        <li>{{ item.product_name }} - Quantity: {{ item.quantity }}</li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No items found.</p>
  {% endif %}
{% endblock %}

templates/delivery_notes/delivery_note_update.html
{% extends "base.html" %}

{% block content %}
  <h1>Edit Delivery Note {{ delivery_note.pk }}</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
{% endblock %}

templates/delivery_notes/detail.html
{% extends "base.html" %}

{% block content %}
  <h1>Delivery Note Details</h1>
  <p><strong>Delivery Note Number:</strong> {{ delivery_note.delivery_note_number }}</p>
  <p><strong>Supplier:</strong> {{ delivery_note.supplier }}</p>
  <p><strong>Delivery Date:</strong> {{ delivery_note.delivery_date }}</p>

  <hr>

  <h2>Items</h2>
  {% if delivery_note.items %}
    <ul>
      {% for item in delivery_note.items %}
        <li>{{ item.product_name }} - Quantity: {{ item.quantity }}</li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No items found.</p>
  {% endif %}
{% endblock %}

templates/delivery_notes/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
  
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        {% comment %} <a class="navbar-brand" href="{% url 'delivery_note_list' %}">Delivery Notes</a> {% endcomment %}
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                 </li>
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNVQ8ew" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {% block js %}{% endblock %}
</body>
</html>

 
  </body>
</html>

templates/delivery_notes/update.html
{% extends "base.html" %}

{% block content %}
  <h1>Edit Delivery Note {{ delivery_note.pk }}</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
  
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        {% comment %} <a class="navbar-brand" href="{% url 'delivery_note_list' %}">Delivery Notes</a> {% endcomment %}
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                 </li>
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNVQ8ew" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {% block js %}{% endblock %}
</body>
</html>

 
  </body>
</html>